name: playground

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    environment:
      name: Playground
      url: https://playground.pysnippet.org/fastapi-oauth2
    runs-on: ubuntu-latest
    steps:
      - name: Run deployment script on server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY_ED25519 }}
          port: ${{ secrets.PORT }}
          script: bash ~/fastapi-oauth2/examples/demonstration/deploy.sh
